### PR TITLE
Add parameter to disable SSL

### PR DESCRIPTION
**Pull request by stintel**

### CODE REVIEW

**Comment by Nosmoht** [comment]
Hi Sintel,

thanks for your request. Could you please change the default to False? Otherwise all other users are forced to add this parameter to there plays if they don't use SSL.

Thanks

**Comment by stintel** [comment]
@Nosmoht before https://github.com/Nosmoht/python-foreman/commit/cac2c417e311dc107eadc46eb75e227175c0faeb the URL scheme was hardcoded to SSL, so afaik it wasn't even possible to use these modules on a Foreman setup without SSL. For this very reason I set it enabled by default, so everyone else using it doesn't need to change anything. Is there something I am missing?

**Comment by Nosmoht** [comment]
Hi stintel, 
thanks for your comment. Seems that i misunderstood you. 
Sorry.

**Comment by stintel** [comment]
@Nosmoht np and thanks for the merge!

**Pull request merged**
